# Generated by Django 4.0.5 on 2022-06-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen_patologica',
            name='edad_paciente',
            field=models.PositiveSmallIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='imagen_patologica',
            name='genero_paciente',
            field=models.CharField(default='hombre', max_length=100),
        ),
    ]
