# Generated by Django 4.0.5 on 2022-06-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alternativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.CharField(max_length=100)),
                ('url_info', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='imagen_patologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_con_patologia', models.ImageField(upload_to='estudio/images/')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
    ]
