# Generated by Django 4.0.5 on 2022-06-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0003_remove_imagen_patologica_edad_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen_patologica',
            name='Informacion_adicional',
            field=models.CharField(default='Dolor estomacal', max_length=200),
        ),
    ]
