# Generated by Django 4.0.4 on 2022-06-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0005_alternativas_descripcion_breve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen_patologica',
            name='edad_paciente_en_años',
        ),
        migrations.RemoveField(
            model_name='imagen_patologica',
            name='genero_paciente',
        ),
        migrations.AlterField(
            model_name='alternativas',
            name='descripcion_breve',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
