# Generated by Django 4.0.5 on 2022-06-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0002_imagen_patologica_edad_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen_patologica',
            name='edad_paciente',
        ),
        migrations.AddField(
            model_name='imagen_patologica',
            name='edad_paciente_en_años',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
