# Generated by Django 4.0.5 on 2022-06-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0004_imagen_patologica_informacion_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativas',
            name='descripcion_breve',
            field=models.CharField(default=' El... es ....', max_length=400),
        ),
        migrations.AlterField(
            model_name='imagen_patologica',
            name='edad_paciente_en_años',
            field=models.CharField(default='tres años', max_length=100),
        ),
    ]
